/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const run: typeof import('../src/utils/index')['run']
  const use: typeof import('../src/utils/index')['use']
  const useAnimation: typeof import('../src/utils/index')['useAnimation']
}
