/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const onKey: typeof import('../src/utils/index')['onKey']
  const run: typeof import('../src/utils/index')['run']
  const use: typeof import('../src/utils/index')['use']
  const useAnimation: typeof import('../src/utils/index')['useAnimation']
  const useKey: typeof import('../src/utils/index')['useKey']
  const useKeyDown: typeof import('../src/utils/index')['useKeyDown']
}
